"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
try:
    import tomllib
except ImportError:
    import tomli as tomllib

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets from .secrets.toml at the project root.
# .secrets.toml が存在しない場合や読み込みに失敗した場合は、空の辞書を使用
try:
    SECRETS_FILE = BASE_DIR / 'config' / '.secrets.toml'
    if SECRETS_FILE.exists():
        with open(SECRETS_FILE, 'rb') as f:
            secrets = tomllib.load(f)
    else:
        secrets = {}
except Exception:
    secrets = {}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# .secrets.toml から取得するように。
SECRET_KEY = secrets.get('SECRET_KEY')
if not SECRET_KEY:
    # 開発用（DEBUG=True）での暫定キー。本番では絶対使ってはダメ。
    SECRET_KEY = (
        'django-insecure-vrmfi#rbgm!q34ri2uiw=8ugq+7-b0cbrz4&*=m*_ud&8+nj#j'
    )

# SECURITY WARNING: don't run with debug turned on in production!
# デフォルトは安全のために False にしとく。開発時は .secrets.toml で True に。
DEBUG = secrets.get('DEBUG', False)

ALLOWED_HOSTS = secrets.get('ALLOWED_HOSTS', [])

SESSION_COOKIE_NAME = secrets.get('SESSION_COOKIE_NAME', 'popon_sessionid')
CSRF_COOKIE_NAME = secrets.get('CSRF_COOKIE_NAME', 'popon_csrftoken')

# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Local apps
    'core',
    'accounts',
    'portal',
    'notification',
    'approvals',
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.common',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Project Name
PROJECT_NAME = "ポポン"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings for development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@example.com'
#
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'YOUR_EMAIL@gmail.com'
# EMAIL_HOST_PASSWORD = 'YOUR_APP_PASSWORD'

SITE_ID = 1  # どのサイト設定を使うかを指定

# Portal Pagination Settings
PORTAL_REQUESTS_PER_PAGE = 20
PORTAL_NOTIFICATIONS_PER_PAGE = 5

try:
    from .local_settings import *  # noqa
except Exception as e:
    import sys
    print(f'Info: {e}: skip.', file=sys.stderr)

#
# 本番環境（DEBUG=False）で安全ではないキーが使われていないかチェック
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ValueError("Security Error: In production (DEBUG=False), you must set a secure SECRET_KEY.")  # noqa: E501

#
